In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('channels.csv')

In [ ]:
df.head(5)

,channel_id,channel_title,niche,description,country,published_at,subscriber_count,total_views,video_count,uploads_playlist_id,...,has_discord,has_external_links,external_links_count,ecosystem_detected,matched_ad_keywords,matched_store_domains,channel_external_links,proportion_videos_with_ad_signals,proportion_videos_with_external_links,parser_data_source
0,UCt7sv-NKh44rHAEb-qCCxvA,Wylsacom,Tech devices and computer peripherals,"Привет, тут у нас просто самый популярный кана...",RU,2011-07-31T17:05:38Z,11500000,3732603938,4400,UUt7sv-NKh44rHAEb-qCCxvA,...,False,True,214,True,реклама|промокод|скидка|ad,aliexpress.ru|ozon.ru,https://wylsa.com/|https://wylsacom.media/|htt...,0.44,0.56,API text analysis
1,UCDF_NIAEkcAUvzxe1DUzaQA,Rozetked,Tech devices and computer peripherals,Такая история\nПо вопросам сотрудничества: ad@...,RU,2011-08-05T09:09:15Z,1950000,786971472,1569,UUDF_NIAEkcAUvzxe1DUzaQA,...,False,True,92,True,реклама|промокод|партнёрство|акция|ad,ozon.ru,https://www.youtube.com/rozetkedplus|https://c...,0.28,0.92,API text analysis
2,UCQXqZtGXzgt1aCATZ2CYCpw,iXBT.com,Tech devices and computer peripherals,IXBT TV — это официальный канал сайта IXBT.com...,TR,2012-05-04T08:39:15Z,183000,72816712,3585,UUQXqZtGXzgt1aCATZ2CYCpw,...,False,True,65,True,реклама|ad,ozon.ru,https://knd.gov.ru/license?id=6762b7cd40af125d...,0.08,0.20,API text analysis
3,UCWtrO-0qP45mQ7pzY9jQHTA,Sponsor Block,Tech devices and computer peripherals,Youtube,US,2019-07-12T05:23:02Z,7,7080,4,UUWtrO-0qP45mQ7pzY9jQHTA,...,False,True,1,False,NaN,NaN,NaN,0.00,0.25,API text analysis
4,UCA0pst15aj1c4bxpTOGBroA,alexgyver,Tech devices and computer peripherals,NaN,NaN,2007-12-21T19:22:41Z,13,0,0,UUA0pst15aj1c4bxpTOGBroA,...,False,False,0,False,NaN,NaN,NaN,0.00,0.00,API text analysis

**AUDIT**



*   Row count

In [ ]:
row_count = df.shape[0]
row_count

44



*   Unique PK count
*   Duplicate PK count

In [ ]:
unique_pk_count = df['channel_id'].value_counts().sum()
duplicate_pk_count = df['channel_id'].duplicated().sum()

print(unique_pk_count)
print(duplicate_pk_count)

44
0



*   Null rate per column

In [ ]:
null_rate_per_column = df.isnull().mean() * 100
null_rate_per_column

channel_id                                0.000000
channel_title                             0.000000
niche                                     0.000000
description                              27.272727
country                                  38.636364
published_at                              0.000000
subscriber_count                          0.000000
total_views                               0.000000
video_count                               0.000000
uploads_playlist_id                       0.000000
data_source                               0.000000
has_ad_keywords                           0.000000
has_affiliate_signals                     0.000000
has_marketplace_links                     0.000000
has_brand_store_links                     0.000000
has_instagram                             0.000000
has_telegram                              0.000000
has_tiktok                                0.000000
has_vk                                    0.000000
has_twitter_x                             0.000000
has_facebook                              0.000000
has_discord                               0.000000
has_external_links                        0.000000
external_links_count                      0.000000
ecosystem_detected                        0.000000
matched_ad_keywords                      34.090909
matched_store_domains                    77.272727
channel_external_links                   65.909091
proportion_videos_with_ad_signals         0.000000
proportion_videos_with_external_links     0.000000
parser_data_source                        0.000000
dtype: float64

In [ ]:
numeric_columns = ['subscriber_count', 'total_views', 'video_count', 'external_links_count',
                   'proportion_videos_with_ad_signals', 'proportion_videos_with_external_links']

print("Name, max, min, median")
for col in numeric_columns:
  max_value = df[col].max()
  min_value = df[col].min()
  median_value = df[col].median()


  print(col, max_value, min_value, median_value)

Name, max, min, median
subscriber_count 21300000 0 39600.0
total_views 5290373546 0 12277957.5
video_count 4400 0 499.5
external_links_count 573 0 31.0
proportion_videos_with_ad_signals 1.0 0.0 0.08
proportion_videos_with_external_links 1.0 0.0 0.2

In [ ]:
df['published_at'] = pd.to_datetime(df['published_at'], errors='coerce')

In [ ]:
for col in numeric_columns:
  df[col] = pd.to_numeric(df[col], errors='coerce')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   channel_id                             44 non-null     object
 1   channel_title                          44 non-null     object
 2   niche                                  44 non-null     object
 3   description                            32 non-null     object
 4   country                                27 non-null     object
 5   published_at                           36 non-null     datetime64[ns, UTC]
 6   subscriber_count                       44 non-null     int64
 7   total_views                            44 non-null     int64
 8   video_count                            44 non-null     int64
 9   uploads_playlist_id                    44 non-null     object
 10  data_source                            44 non-null     object
 11  has_ad_keywords                        44 non-null     bool
 12  has_affiliate_signals                  44 non-null     bool
 13  has_marketplace_links                  44 non-null     bool
 14  has_brand_store_links                  44 non-null     bool
 15  has_instagram                          44 non-null     bool
 16  has_telegram                           44 non-null     bool
 17  has_tiktok                             44 non-null     bool
 18  has_vk                                 44 non-null     bool
 19  has_twitter_x                          44 non-null     bool
 20  has_facebook                           44 non-null     bool
 21  has_discord                            44 non-null     bool
 22  has_external_links                     44 non-null     bool
 23  external_links_count                   44 non-null     int64
 24  ecosystem_detected                     44 non-null     bool
 25  matched_ad_keywords                    29 non-null     object
 26  matched_store_domains                  10 non-null     object
 27  channel_external_links                 15 non-null     object
 28  proportion_videos_with_ad_signals      44 non-null     float64
 29  proportion_videos_with_external_links  44 non-null     float64
 30  parser_data_source                     44 non-null     object
dtypes: bool(13), datetime64[ns, UTC](1), float64(2), int64(4), object(11)
memory usage: 6.9+ KB

In [ ]:
def parse_list(x):
  if pd.isna(x) or x == '':
    return []
  return [i.strip() for i in str(x).split('|')]

In [ ]:
string_columns = ['matched_ad_keywords', 'matched_store_domains', 'channel_external_links']

for col in string_columns:
  df[col] = df[col].apply(parse_list)

In [ ]:
df.head(5)

,channel_id,channel_title,niche,description,country,published_at,subscriber_count,total_views,video_count,uploads_playlist_id,...,has_discord,has_external_links,external_links_count,ecosystem_detected,matched_ad_keywords,matched_store_domains,channel_external_links,proportion_videos_with_ad_signals,proportion_videos_with_external_links,parser_data_source
0,UCt7sv-NKh44rHAEb-qCCxvA,Wylsacom,Tech devices and computer peripherals,"Привет, тут у нас просто самый популярный кана...",RU,2011-07-31 17:05:38+00:00,11500000,3732603938,4400,UUt7sv-NKh44rHAEb-qCCxvA,...,False,True,214,True,"[реклама, промокод, скидка, ad]","[aliexpress.ru, ozon.ru]","[https://wylsa.com/, https://wylsacom.media/, ...",0.44,0.56,API text analysis
1,UCDF_NIAEkcAUvzxe1DUzaQA,Rozetked,Tech devices and computer peripherals,Такая история\nПо вопросам сотрудничества: ad@...,RU,2011-08-05 09:09:15+00:00,1950000,786971472,1569,UUDF_NIAEkcAUvzxe1DUzaQA,...,False,True,92,True,"[реклама, промокод, партнёрство, акция, ad]",[ozon.ru],"[https://www.youtube.com/rozetkedplus, https:/...",0.28,0.92,API text analysis
2,UCQXqZtGXzgt1aCATZ2CYCpw,iXBT.com,Tech devices and computer peripherals,IXBT TV — это официальный канал сайта IXBT.com...,TR,2012-05-04 08:39:15+00:00,183000,72816712,3585,UUQXqZtGXzgt1aCATZ2CYCpw,...,False,True,65,True,"[реклама, ad]",[ozon.ru],[https://knd.gov.ru/license?id=6762b7cd40af125...,0.08,0.20,API text analysis
3,UCWtrO-0qP45mQ7pzY9jQHTA,Sponsor Block,Tech devices and computer peripherals,Youtube,US,2019-07-12 05:23:02+00:00,7,7080,4,UUWtrO-0qP45mQ7pzY9jQHTA,...,False,True,1,False,[],[],[],0.00,0.25,API text analysis
4,UCA0pst15aj1c4bxpTOGBroA,alexgyver,Tech devices and computer peripherals,NaN,NaN,2007-12-21 19:22:41+00:00,13,0,0,UUA0pst15aj1c4bxpTOGBroA,...,False,False,0,False,[],[],[],0.00,0.00,API text analysis

In [ ]:
mask = df['channel_title'] == 'Sponsor Block'
print(mask.sum())

1

In [ ]:
total_views_zero = df[df['total_views'] == 0].index
df = df.drop(total_views_zero)

In [ ]:
del df['data_source']
del df['parser_data_source']

In [ ]:
subs_less_than_5000 = df[df['subscriber_count'] < 5000].index
df = df.drop(subs_less_than_5000)

In [ ]:
df['country'] = df['country'].fillna('unknown')

In [ ]:
del df['niche']

In [ ]:
df['views_per_subscriber'] = df['total_views']/df['subscriber_count']

In [ ]:
social_cols = ['has_instagram', 'has_telegram', 'has_tiktok',
    'has_vk', 'has_twitter_x', 'has_facebook', 'has_discord']

df['ecosystem_score'] = df[social_cols].sum(axis=1)

In [ ]:
df

,channel_id,channel_title,description,country,published_at,subscriber_count,total_views,video_count,uploads_playlist_id,has_ad_keywords,...,has_external_links,external_links_count,ecosystem_detected,matched_ad_keywords,matched_store_domains,channel_external_links,proportion_videos_with_ad_signals,proportion_videos_with_external_links,views_per_subscriber,ecosystem_score
0,UCt7sv-NKh44rHAEb-qCCxvA,Wylsacom,"Привет, тут у нас просто самый популярный кана...",RU,2011-07-31 17:05:38+00:00,11500000,3732603938,4400,UUt7sv-NKh44rHAEb-qCCxvA,True,...,True,214,True,"[реклама, промокод, скидка, ad]","[aliexpress.ru, ozon.ru]","[https://wylsa.com/, https://wylsacom.media/, ...",0.44,0.56,324.574255,0
1,UCDF_NIAEkcAUvzxe1DUzaQA,Rozetked,Такая история\nПо вопросам сотрудничества: ad@...,RU,2011-08-05 09:09:15+00:00,1950000,786971472,1569,UUDF_NIAEkcAUvzxe1DUzaQA,True,...,True,92,True,"[реклама, промокод, партнёрство, акция, ad]",[ozon.ru],"[https://www.youtube.com/rozetkedplus, https:/...",0.28,0.92,403.575114,0
2,UCQXqZtGXzgt1aCATZ2CYCpw,iXBT.com,IXBT TV — это официальный канал сайта IXBT.com...,TR,2012-05-04 08:39:15+00:00,183000,72816712,3585,UUQXqZtGXzgt1aCATZ2CYCpw,True,...,True,65,True,"[реклама, ad]",[ozon.ru],[https://knd.gov.ru/license?id=6762b7cd40af125...,0.08,0.20,397.905530,0
5,UCXNUrJGI6-5hv6xcncrQq8g,Romancev768,Фишки о которых ты не знал! Коротко и по делу!...,RU,NaT,1670000,2379482230,3261,UUXNUrJGI6-5hv6xcncrQq8g,True,...,True,20,True,"[сотрудничество, промокод, скидка, ad]",[],"[https://www.tiktok.com/@romancev768, https://...",0.06,0.14,1424.839659,2
7,UCpEFdIYj0PT4izVX1ZhYvxA,Valaybalalay,"Valaybalalay - канал, на котором я копаюсь в л...",MX,2013-09-06 11:43:08+00:00,973000,274378142,617,UUpEFdIYj0PT4izVX1ZhYvxA,True,...,True,224,True,"[сотрудничество, реклама, промокод, скидка, ак...",[],"[https://t.me/Neznanov_Igor, https://boosty.to...",0.82,0.82,281.991924,2
10,UCmbzthMYaX8FAe_cZSrGMrA,MobileReviewcom,"Сайт mobile-review.com посвящен технологиям, р...",US,2009-10-13 00:35:31+00:00,398000,18663879,950,UUmbzthMYaX8FAe_cZSrGMrA,True,...,True,344,True,[ad],[],[https://gosuslugi.ru/snet/67a08c25de97c91600d...,0.02,0.98,46.894168,0
11,UCQ18THOcZ8nIP-A3ZCqqZwA,BIG GEEK,"С душой и изюминкой рассказываем о гаджетах, а...",RU,2011-01-24 01:01:41+00:00,1430000,176423158,1764,UUQ18THOcZ8nIP-A3ZCqqZwA,True,...,True,111,True,"[реклама, промокод, ad]",[],[https://www.gosuslugi.ru/snet/67a4693ca16f1b5...,0.20,0.20,123.372838,5
13,UCnhtNyHVK3vohIW4x1GnOAg,Quke.ru,"Обзоры новых смартфонов, сравнения, развернуты...",RU,2009-05-16 15:54:48+00:00,327000,136416955,2634,UUnhtNyHVK3vohIW4x1GnOAg,True,...,True,346,True,"[referral, ad]","[ozon.ru, wildberries.ru]",[],0.82,0.96,417.177232,0
14,UCgkaE_eh-REB8jXxewzoXbg,SMART ОБЗОР,Подробные обзоры на новинки мобильной индустри...,RU,2016-11-12 14:38:50+00:00,140000,45477211,596,UUgkaE_eh-REB8jXxewzoXbg,True,...,True,219,True,"[реклама, скидка, ad]","[aliexpress.ru, ozon.ru]","[https://t.me/smartobzorchannel, https://vk.co...",0.50,1.00,324.837221,2
15,UCF42abSQuakkeijvlT_qGtQ,#ЧУДОТЕХНИКИ с Георгием Беловым,Контакты\n\nПо поводу рекламы и приглашений на...,unknown,2012-04-05 14:25:38+00:00,234000,84781517,894,UUF42abSQuakkeijvlT_qGtQ,True,...,True,140,True,"[реклама, промокод, скидка, акция, ad]",[],"[https://vk.com/belov_gera, https://t.me/drink...",0.36,0.50,362.314175,2
18,UCMcC_43zGHttf9bY-xJOTwA,egoroff_channel,"Приветствую, меня зовут Егоров Артем. Мой кан...",RU,2015-03-02 20:59:14+00:00,141000,17984525,605,UUMcC_43zGHttf9bY-xJOTwA,True,...,True,325,True,"[промокод, скидка, ad]",[],[https://www.youtube.com/channel/UCMcC_43zGHtt...,0.08,0.82,127.549823,1
19,UCIIt69f5D44s2cdb9vXQNzA,loftblog,LoftBlog — это лучшее место для изучения it-те...,RU,2013-03-20 19:40:05+00:00,373000,38855319,1732,UUIIt69f5D44s2cdb9vXQNzA,True,...,True,87,True,"[промокод, скидка, ad]",[],[],0.52,0.88,104.169756,0
20,UCDzGdB9TTgFm8jRXn1tBdoA,Ulbi TV,Привет друзья!) Меня зовут Ульби Тимур. Я full...,RU,NaT,330000,34345719,181,UUDzGdB9TTgFm8jRXn1tBdoA,True,...,True,303,True,"[реклама, промокод, скидка, акция, ad]",[],"[https://ulbitv.ru/frontend, https://t.me/vaca...",0.32,0.98,104.077936,1
21,UC2Ev-rDSHBov0ZMChesLfrg,ITDoctor,Меня зовут Исмаил Усеинов. В 2017 году основал...,RU,2017-09-01 15:26:41+00:00,74300,10062434,1179,UU2Ev-rDSHBov0ZMChesLfrg,True,...,True,480,True,[ad],[],[],0.06,1.00,135.429798,0
25,UCodIRuNfsp09zPs1bFxNSRw,PurpleSchool | Anton Larichev,Канал о разработке и обучающие видео по JavaSc...,RU,NaT,58300,14493481,1229,UUodIRuNfsp09zPs1bFxNSRw,True,...,True,42,True,[ad],[],"[https://purpleschool.ru, https://t.me/purple_...",0.08,0.08,248.601732,2
29,UC2D9iDnY_ZD7sozyhN-Bq4A,Remonter,"Приветствую, дорогой друг! Это канал по ремонт...",RU,2010-03-28 17:56:36+00:00,1070000,361320906,1152,UU2D9iDnY_ZD7sozyhN-Bq4A,True,...,True,573,True,"[реклама, промокод, ad]","[aliexpress.com, aliexpress.ru, dns-shop.ru, o...","[https://taplink.cc/remonter_donate, https://g...",0.22,1.00,337.683090,0
32,UCSpU8Y1aoqBSAwh8DBpiM9A,Keddr.com,Робимо для вас техно-годноту з 2010 року!,UA,2010-10-23 12:09:47+00:00,623000,220777177,4100,UUSpU8Y1aoqBSAwh8DBpiM9A,True,...,True,358,True,"[реклама, промокод, ad]",[aliexpress.com],[],0.18,0.60,354.377491,0
33,UC7hhJzOlrPOdM2jmrmD59XA,Gadget Page,"Gadget Page - то самое место, где ты можешь уз...",FR,2016-05-17 14:06:46+00:00,115000,35474137,666,UU7hhJzOlrPOdM2jmrmD59XA,True,...,True,374,True,"[реклама, промокод, скидка, купон, ad]","[aliexpress.com, aliexpress.ru, amazon.co, ama...",[],0.96,0.96,308.470757,0
37,UCHFNDph3zTYh8-hwofOVXsg,stupidmadworld,Техноблог stupidmadworld. Рассказываю о хороше...,KZ,2013-10-21 17:45:15+00:00,846000,221359911,1454,UUHFNDph3zTYh8-hwofOVXsg,True,...,True,314,True,"[реклама, промокод, купон, ad]",[],[],0.76,0.78,261.654741,0
38,UCe_vXdMrHHseZ_esYUskSBw,CrazyRussianHacker,Fan Mail or if you want me review your product...,US,2012-05-18 19:29:15+00:00,12000000,3795910170,2954,UUe_vXdMrHHseZ_esYUskSBw,True,...,True,2,True,[ad],[],[],0.50,0.04,316.325848,0
39,UCU_yU4xGT9hrVFo6euH8LLw,SlivkiShow,SlivkiShow is a place where crazy ideas turn i...,IT,2012-12-11 08:59:55+00:00,21300000,5290373546,517,UUU_yU4xGT9hrVFo6euH8LLw,True,...,True,221,True,"[сотрудничество, промокод, ad]",[],[],1.00,0.92,248.374345,0
40,UCSF6ewY9LS8GnbphwvnZpUg,Mamix,Реклама/Сотрудничество:\nmamix.biz@yandex.com\...,US,2017-02-01 07:21:15+00:00,15600000,2951875403,482,UUSF6ewY9LS8GnbphwvnZpUg,True,...,True,204,True,"[сотрудничество, реклама, промокод]",[ozon.ru],"[https://rutube.ru/channel/70619219/, https://...",0.04,0.98,189.222782,0
43,UCA-JK7chBxEsGHQs3m6UK5A,Device Lab,"On my channel, you can always watch reviews an...",US,2018-12-15 14:00:22+00:00,20900,15581160,2043,UUA-JK7chBxEsGHQs3m6UK5A,True,...,True,151,True,[ad],[],[],0.22,0.78,745.510048,0

In [ ]:
df.reset_index(drop=True, inplace=True)

In [ ]:
df

,channel_id,channel_title,description,country,published_at,subscriber_count,total_views,video_count,uploads_playlist_id,has_ad_keywords,...,has_external_links,external_links_count,ecosystem_detected,matched_ad_keywords,matched_store_domains,channel_external_links,proportion_videos_with_ad_signals,proportion_videos_with_external_links,views_per_subscriber,ecosystem_score
0,UCt7sv-NKh44rHAEb-qCCxvA,Wylsacom,"Привет, тут у нас просто самый популярный кана...",RU,2011-07-31 17:05:38+00:00,11500000,3732603938,4400,UUt7sv-NKh44rHAEb-qCCxvA,True,...,True,214,True,"[реклама, промокод, скидка, ad]","[aliexpress.ru, ozon.ru]","[https://wylsa.com/, https://wylsacom.media/, ...",0.44,0.56,324.574255,0
1,UCDF_NIAEkcAUvzxe1DUzaQA,Rozetked,Такая история\nПо вопросам сотрудничества: ad@...,RU,2011-08-05 09:09:15+00:00,1950000,786971472,1569,UUDF_NIAEkcAUvzxe1DUzaQA,True,...,True,92,True,"[реклама, промокод, партнёрство, акция, ad]",[ozon.ru],"[https://www.youtube.com/rozetkedplus, https:/...",0.28,0.92,403.575114,0
2,UCQXqZtGXzgt1aCATZ2CYCpw,iXBT.com,IXBT TV — это официальный канал сайта IXBT.com...,TR,2012-05-04 08:39:15+00:00,183000,72816712,3585,UUQXqZtGXzgt1aCATZ2CYCpw,True,...,True,65,True,"[реклама, ad]",[ozon.ru],[https://knd.gov.ru/license?id=6762b7cd40af125...,0.08,0.20,397.905530,0
3,UCXNUrJGI6-5hv6xcncrQq8g,Romancev768,Фишки о которых ты не знал! Коротко и по делу!...,RU,NaT,1670000,2379482230,3261,UUXNUrJGI6-5hv6xcncrQq8g,True,...,True,20,True,"[сотрудничество, промокод, скидка, ad]",[],"[https://www.tiktok.com/@romancev768, https://...",0.06,0.14,1424.839659,2
4,UCpEFdIYj0PT4izVX1ZhYvxA,Valaybalalay,"Valaybalalay - канал, на котором я копаюсь в л...",MX,2013-09-06 11:43:08+00:00,973000,274378142,617,UUpEFdIYj0PT4izVX1ZhYvxA,True,...,True,224,True,"[сотрудничество, реклама, промокод, скидка, ак...",[],"[https://t.me/Neznanov_Igor, https://boosty.to...",0.82,0.82,281.991924,2
5,UCmbzthMYaX8FAe_cZSrGMrA,MobileReviewcom,"Сайт mobile-review.com посвящен технологиям, р...",US,2009-10-13 00:35:31+00:00,398000,18663879,950,UUmbzthMYaX8FAe_cZSrGMrA,True,...,True,344,True,[ad],[],[https://gosuslugi.ru/snet/67a08c25de97c91600d...,0.02,0.98,46.894168,0
6,UCQ18THOcZ8nIP-A3ZCqqZwA,BIG GEEK,"С душой и изюминкой рассказываем о гаджетах, а...",RU,2011-01-24 01:01:41+00:00,1430000,176423158,1764,UUQ18THOcZ8nIP-A3ZCqqZwA,True,...,True,111,True,"[реклама, промокод, ad]",[],[https://www.gosuslugi.ru/snet/67a4693ca16f1b5...,0.20,0.20,123.372838,5
7,UCnhtNyHVK3vohIW4x1GnOAg,Quke.ru,"Обзоры новых смартфонов, сравнения, развернуты...",RU,2009-05-16 15:54:48+00:00,327000,136416955,2634,UUnhtNyHVK3vohIW4x1GnOAg,True,...,True,346,True,"[referral, ad]","[ozon.ru, wildberries.ru]",[],0.82,0.96,417.177232,0
8,UCgkaE_eh-REB8jXxewzoXbg,SMART ОБЗОР,Подробные обзоры на новинки мобильной индустри...,RU,2016-11-12 14:38:50+00:00,140000,45477211,596,UUgkaE_eh-REB8jXxewzoXbg,True,...,True,219,True,"[реклама, скидка, ad]","[aliexpress.ru, ozon.ru]","[https://t.me/smartobzorchannel, https://vk.co...",0.50,1.00,324.837221,2
9,UCF42abSQuakkeijvlT_qGtQ,#ЧУДОТЕХНИКИ с Георгием Беловым,Контакты\n\nПо поводу рекламы и приглашений на...,unknown,2012-04-05 14:25:38+00:00,234000,84781517,894,UUF42abSQuakkeijvlT_qGtQ,True,...,True,140,True,"[реклама, промокод, скидка, акция, ad]",[],"[https://vk.com/belov_gera, https://t.me/drink...",0.36,0.50,362.314175,2
10,UCMcC_43zGHttf9bY-xJOTwA,egoroff_channel,"Приветствую, меня зовут Егоров Артем. Мой кан...",RU,2015-03-02 20:59:14+00:00,141000,17984525,605,UUMcC_43zGHttf9bY-xJOTwA,True,...,True,325,True,"[промокод, скидка, ad]",[],[https://www.youtube.com/channel/UCMcC_43zGHtt...,0.08,0.82,127.549823,1
11,UCIIt69f5D44s2cdb9vXQNzA,loftblog,LoftBlog — это лучшее место для изучения it-те...,RU,2013-03-20 19:40:05+00:00,373000,38855319,1732,UUIIt69f5D44s2cdb9vXQNzA,True,...,True,87,True,"[промокод, скидка, ad]",[],[],0.52,0.88,104.169756,0
12,UCDzGdB9TTgFm8jRXn1tBdoA,Ulbi TV,Привет друзья!) Меня зовут Ульби Тимур. Я full...,RU,NaT,330000,34345719,181,UUDzGdB9TTgFm8jRXn1tBdoA,True,...,True,303,True,"[реклама, промокод, скидка, акция, ad]",[],"[https://ulbitv.ru/frontend, https://t.me/vaca...",0.32,0.98,104.077936,1
13,UC2Ev-rDSHBov0ZMChesLfrg,ITDoctor,Меня зовут Исмаил Усеинов. В 2017 году основал...,RU,2017-09-01 15:26:41+00:00,74300,10062434,1179,UU2Ev-rDSHBov0ZMChesLfrg,True,...,True,480,True,[ad],[],[],0.06,1.00,135.429798,0
14,UCodIRuNfsp09zPs1bFxNSRw,PurpleSchool | Anton Larichev,Канал о разработке и обучающие видео по JavaSc...,RU,NaT,58300,14493481,1229,UUodIRuNfsp09zPs1bFxNSRw,True,...,True,42,True,[ad],[],"[https://purpleschool.ru, https://t.me/purple_...",0.08,0.08,248.601732,2
15,UC2D9iDnY_ZD7sozyhN-Bq4A,Remonter,"Приветствую, дорогой друг! Это канал по ремонт...",RU,2010-03-28 17:56:36+00:00,1070000,361320906,1152,UU2D9iDnY_ZD7sozyhN-Bq4A,True,...,True,573,True,"[реклама, промокод, ad]","[aliexpress.com, aliexpress.ru, dns-shop.ru, o...","[https://taplink.cc/remonter_donate, https://g...",0.22,1.00,337.683090,0
16,UCSpU8Y1aoqBSAwh8DBpiM9A,Keddr.com,Робимо для вас техно-годноту з 2010 року!,UA,2010-10-23 12:09:47+00:00,623000,220777177,4100,UUSpU8Y1aoqBSAwh8DBpiM9A,True,...,True,358,True,"[реклама, промокод, ad]",[aliexpress.com],[],0.18,0.60,354.377491,0
17,UC7hhJzOlrPOdM2jmrmD59XA,Gadget Page,"Gadget Page - то самое место, где ты можешь уз...",FR,2016-05-17 14:06:46+00:00,115000,35474137,666,UU7hhJzOlrPOdM2jmrmD59XA,True,...,True,374,True,"[реклама, промокод, скидка, купон, ad]","[aliexpress.com, aliexpress.ru, amazon.co, ama...",[],0.96,0.96,308.470757,0
18,UCHFNDph3zTYh8-hwofOVXsg,stupidmadworld,Техноблог stupidmadworld. Рассказываю о хороше...,KZ,2013-10-21 17:45:15+00:00,846000,221359911,1454,UUHFNDph3zTYh8-hwofOVXsg,True,...,True,314,True,"[реклама, промокод, купон, ad]",[],[],0.76,0.78,261.654741,0
19,UCe_vXdMrHHseZ_esYUskSBw,CrazyRussianHacker,Fan Mail or if you want me review your product...,US,2012-05-18 19:29:15+00:00,12000000,3795910170,2954,UUe_vXdMrHHseZ_esYUskSBw,True,...,True,2,True,[ad],[],[],0.50,0.04,316.325848,0
20,UCU_yU4xGT9hrVFo6euH8LLw,SlivkiShow,SlivkiShow is a place where crazy ideas turn i...,IT,2012-12-11 08:59:55+00:00,21300000,5290373546,517,UUU_yU4xGT9hrVFo6euH8LLw,True,...,True,221,True,"[сотрудничество, промокод, ad]",[],[],1.00,0.92,248.374345,0
21,UCSF6ewY9LS8GnbphwvnZpUg,Mamix,Реклама/Сотрудничество:\nmamix.biz@yandex.com\...,US,2017-02-01 07:21:15+00:00,15600000,2951875403,482,UUSF6ewY9LS8GnbphwvnZpUg,True,...,True,204,True,"[сотрудничество, реклама, промокод]",[ozon.ru],"[https://rutube.ru/channel/70619219/, https://...",0.04,0.98,189.222782,0
22,UCA-JK7chBxEsGHQs3m6UK5A,Device Lab,"On my channel, you can always watch reviews an...",US,2018-12-15 14:00:22+00:00,20900,15581160,2043,UUA-JK7chBxEsGHQs3m6UK5A,True,...,True,151,True,[ad],[],[],0.22,0.78,745.510048,0

In [ ]:
df.to_csv('channels_cleaned.csv', index=False)

In [ ]:
df.isna().sum()

channel_id                               0
channel_title                            0
description                              0
country                                  0
published_at                             3
subscriber_count                         0
total_views                              0
video_count                              0
uploads_playlist_id                      0
has_ad_keywords                          0
has_affiliate_signals                    0
has_marketplace_links                    0
has_brand_store_links                    0
has_instagram                            0
has_telegram                             0
has_tiktok                               0
has_vk                                   0
has_twitter_x                            0
has_facebook                             0
has_discord                              0
has_external_links                       0
external_links_count                     0
ecosystem_detected                       0
matched_ad_keywords                      0
matched_store_domains                    0
channel_external_links                   0
proportion_videos_with_ad_signals        0
proportion_videos_with_external_links    0
views_per_subscriber                     0
ecosystem_score                          0
dtype: int64