In [3]:
import pandas as pd
import numpy as np
import ast

In [4]:
df = pd.read_csv('videos.csv')
df_channels = pd.read_csv('channels_cleaned_postgres.csv', sep=';')

In [5]:
df.head()

,channel_id,video_id,video_url,title,published_at,duration,duration_seconds,tags,description,view_count,like_count,comment_count,data_source,has_ad_keywords,matched_ad_keywords,has_external_links,external_links_count,external_links
0,UCt7sv-NKh44rHAEb-qCCxvA,ZUU3OIfSRNE,https://www.youtube.com/watch?v=ZUU3OIfSRNE,"Умные шахматы, где фигуры движутся сами! Магия!",2026-03-19T16:20:59Z,15m 9s,909,iPhone|Apple|wylsa|Wylsacom|Айфон|Вилса|Вилсак...,Лимитированный игровой ноутбук MSI Titan Drago...,13018,1458,104,API text analysis,True,реклама,True,8,https://clck.ru/3Sdtu3|https://t.me/Wylsared|h...
1,UCt7sv-NKh44rHAEb-qCCxvA,pZSK9k7RdpA,https://www.youtube.com/watch?v=pZSK9k7RdpA,"Посылки из Китая: ОЧЕНЬ дорогой регистратор, M...",2026-03-17T15:20:53Z,21m 16s,1276,iPhone|Apple|wylsa|Wylsacom|Айфон|Вилса|Вилсак...,Илья в Телеграме — https://t.me/kazakof\nНаши ...,122067,2621,169,API text analysis,True,реклама,True,13,https://t.me/kazakof|https://biggeek.ru|https:...
2,UCt7sv-NKh44rHAEb-qCCxvA,KF73tDDafwk,https://www.youtube.com/watch?v=KF73tDDafwk,Посылка от подписчика для Wylsacom и его больш...,2026-03-17T11:42:15Z,1m 29s,89,NaN,NaN,204982,4081,68,API text analysis,False,NaN,False,0,NaN
3,UCt7sv-NKh44rHAEb-qCCxvA,Ij5lid7NzXo,https://www.youtube.com/watch?v=Ij5lid7NzXo,Когда тест пошёл не по плану!,2026-03-15T09:58:57Z,22s,22,NaN,NaN,636113,6446,131,API text analysis,False,NaN,False,0,NaN
4,UCt7sv-NKh44rHAEb-qCCxvA,Wh6Tz00KpbQ,https://www.youtube.com/watch?v=Wh6Tz00KpbQ,Новый MacBook Neo vs. игры. Бессмысленно и бес...,2026-03-14T15:14:26Z,13m 17s,797,iPhone|Apple|wylsa|Wylsacom|Айфон|Вилса|Вилсак...,Илья в Телеграме — https://t.me/kazakof\nНаши ...,241578,5639,482,API text analysis,True,реклама,True,9,https://t.me/kazakof|https://biggeek.ru|https:...

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1400 entries, 0 to 1399
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   channel_id            1400 non-null   object
 1   video_id              1400 non-null   object
 2   video_url             1400 non-null   object
 3   title                 1400 non-null   object
 4   published_at          1400 non-null   object
 5   duration              1400 non-null   object
 6   duration_seconds      1400 non-null   int64
 7   tags                  834 non-null    object
 8   description           1105 non-null   object
 9   view_count            1400 non-null   int64
 10  like_count            1400 non-null   int64
 11  comment_count         1400 non-null   int64
 12  data_source           1400 non-null   object
 13  has_ad_keywords       1400 non-null   bool
 14  matched_ad_keywords   451 non-null    object
 15  has_external_links    1400 non-null   bool
 16  external_links_count  1400 non-null   int64
 17  external_links        835 non-null    object
dtypes: bool(2), int64(5), object(11)
memory usage: 177.9+ KB

In [7]:
df = df[df['channel_id'].isin(df_channels['channel_id'])]
df

,channel_id,video_id,video_url,title,published_at,duration,duration_seconds,tags,description,view_count,like_count,comment_count,data_source,has_ad_keywords,matched_ad_keywords,has_external_links,external_links_count,external_links
0,UCt7sv-NKh44rHAEb-qCCxvA,ZUU3OIfSRNE,https://www.youtube.com/watch?v=ZUU3OIfSRNE,"Умные шахматы, где фигуры движутся сами! Магия!",2026-03-19T16:20:59Z,15m 9s,909,iPhone|Apple|wylsa|Wylsacom|Айфон|Вилса|Вилсак...,Лимитированный игровой ноутбук MSI Titan Drago...,13018,1458,104,API text analysis,True,реклама,True,8,https://clck.ru/3Sdtu3|https://t.me/Wylsared|h...
1,UCt7sv-NKh44rHAEb-qCCxvA,pZSK9k7RdpA,https://www.youtube.com/watch?v=pZSK9k7RdpA,"Посылки из Китая: ОЧЕНЬ дорогой регистратор, M...",2026-03-17T15:20:53Z,21m 16s,1276,iPhone|Apple|wylsa|Wylsacom|Айфон|Вилса|Вилсак...,Илья в Телеграме — https://t.me/kazakof\nНаши ...,122067,2621,169,API text analysis,True,реклама,True,13,https://t.me/kazakof|https://biggeek.ru|https:...
2,UCt7sv-NKh44rHAEb-qCCxvA,KF73tDDafwk,https://www.youtube.com/watch?v=KF73tDDafwk,Посылка от подписчика для Wylsacom и его больш...,2026-03-17T11:42:15Z,1m 29s,89,NaN,NaN,204982,4081,68,API text analysis,False,NaN,False,0,NaN
3,UCt7sv-NKh44rHAEb-qCCxvA,Ij5lid7NzXo,https://www.youtube.com/watch?v=Ij5lid7NzXo,Когда тест пошёл не по плану!,2026-03-15T09:58:57Z,22s,22,NaN,NaN,636113,6446,131,API text analysis,False,NaN,False,0,NaN
4,UCt7sv-NKh44rHAEb-qCCxvA,Wh6Tz00KpbQ,https://www.youtube.com/watch?v=Wh6Tz00KpbQ,Новый MacBook Neo vs. игры. Бессмысленно и бес...,2026-03-14T15:14:26Z,13m 17s,797,iPhone|Apple|wylsa|Wylsacom|Айфон|Вилса|Вилсак...,Илья в Телеграме — https://t.me/kazakof\nНаши ...,241578,5639,482,API text analysis,True,реклама,True,9,https://t.me/kazakof|https://biggeek.ru|https:...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1395,UCA-JK7chBxEsGHQs3m6UK5A,orbeWPH8XCs,https://www.youtube.com/watch?v=orbeWPH8XCs,TOP—5. Best Gaming Monitors (144Hz–165Hz) Febr...,2026-02-23T22:01:00Z,32s,32,comparison|cpu|gpu|intel|amd|nvidia|geforce|ra...,NaN,840,5,0,API text analysis,False,NaN,False,0,NaN
1396,UCA-JK7chBxEsGHQs3m6UK5A,px3nom_-Y6I,https://www.youtube.com/watch?v=px3nom_-Y6I,TOP—5. Best Workstation Laptops 2026,2026-02-23T22:00:54Z,5m 24s,324,comparison|cpu|gpu|intel|amd|nvidia|geforce|ra...,HP ‎TPN-I139\nAmazon https://flozes.com/a?shop...,200,2,1,API text analysis,True,ad,True,5,https://flozes.com/a?shop=aus&id=HP-TPN-I139-B...
1397,UCA-JK7chBxEsGHQs3m6UK5A,_ZmC7Kg2H7E,https://www.youtube.com/watch?v=_ZmC7Kg2H7E,Dell S2425HSM Monitor | TEST | English,2026-02-23T18:00:46Z,3m 59s,239,comparison|cpu|gpu|intel|amd|nvidia|geforce|ra...,Amazon https://flozes.com/a?shop=aus&id=Dell-S...,394,5,2,API text analysis,False,NaN,True,1,https://flozes.com/a?shop=aus&id=Dell-S2425HSM...
1398,UCA-JK7chBxEsGHQs3m6UK5A,dOjsTS_qCiI,https://www.youtube.com/watch?v=dOjsTS_qCiI,TOP—5. Best Gaming Monitors (360Hz–540Hz) Marc...,2026-02-23T00:00:40Z,5m 46s,346,comparison|cpu|gpu|intel|amd|nvidia|geforce|ra...,LG ‎27G810A-B.AUS\nAmazon https://flozes.com/a...,99,5,1,API text analysis,False,NaN,True,5,https://flozes.com/a?shop=aus&id=LG-27G810A-Be...
1399,UCA-JK7chBxEsGHQs3m6UK5A,Yssj-DxENaA,https://www.youtube.com/watch?v=Yssj-DxENaA,TOP—5. Best Gaming Monitors (144Hz–165Hz) Marc...,2026-02-22T22:00:36Z,5m 14s,314,comparison|cpu|gpu|intel|amd|nvidia|geforce|ra...,‎Dell 24 Plus Monitor - S2425HSM\nAmazon https...,84,2,1,API text analysis,False,NaN,True,5,https://flozes.com/a?shop=aus&id=Dell-24-Plus-...

In [8]:
df['video_id'].duplicated().sum()

np.int64(0)

In [9]:
df = df.fillna('')

In [10]:
df['published_at'] = df['published_at'].replace('', pd.NA)

In [11]:
df['published_at'] = pd.to_datetime(df['published_at'], errors='coerce')

In [12]:
numeric_cols = ['duration_seconds', 'view_count', 'like_count', 'comment_count', 'external_links_count']

In [13]:
for col in numeric_cols:
  df[col] = pd.to_numeric(df[col], errors='coerce')

In [14]:
def parse_list(x):
  if pd.isna(x) or x == '':
    return []
  return [i.strip() for i in str(x).split('|')]

In [15]:
cols_to_parse = ['tags', 'matched_ad_keywords', 'external_links']

In [16]:
for col in cols_to_parse:
  df[col] = df[col].apply(parse_list)

In [17]:
del df['data_source']

Min, Max and Median of numeric columns

In [18]:
summary_table = df[numeric_cols].describe().T[['min', 'max', '50%']]
summary_table = summary_table.rename(columns={'50%': 'median'})
print(summary_table)

                       min         max   median
duration_seconds      11.0     12829.0    501.5
view_count            21.0  57000513.0  25749.0
like_count             0.0   2542244.0    795.5
comment_count          0.0     30109.0     80.5
external_links_count   0.0        22.0      4.0

Mininum value of each column is 0

In [19]:
zero_view = df['view_count'] <= 0
zero_like = df['like_count'] <= 0
zero_comment = df['comment_count'] <= 0
zero_duration_second = df['duration_seconds'] <= 0

print("Zero view video count:", zero_view.sum())
print("Zero like video count:", zero_like.sum())
print("Zero comment video count:", zero_comment.sum())
print("Zero duration seconds video count:", zero_duration_second.sum())

Zero view video count: 0
Zero like video count: 2
Zero comment video count: 56
Zero duration seconds video count: 0

In [20]:
df[zero_comment & zero_like & (df['duration_seconds'] > 60)]

,channel_id,video_id,video_url,title,published_at,duration,duration_seconds,tags,description,view_count,like_count,comment_count,has_ad_keywords,matched_ad_keywords,has_external_links,external_links_count,external_links
1352,UCA-JK7chBxEsGHQs3m6UK5A,XfikptL-XhE,https://www.youtube.com/watch?v=XfikptL-XhE,TOP—5. Best Gaming Monitors (Under $300) March...,2026-03-16 22:00:38+00:00,6m 36s,396,"[comparison, cpu, gpu, intel, amd, nvidia, gef...",Sceptre ‎C325B-FWD240.A1\nAmazon https://floze...,102,0,0,False,[],True,5,[https://flozes.com/a?shop=aus&id=Sceptre-C325...
1354,UCA-JK7chBxEsGHQs3m6UK5A,jJhbXriDxpw,https://www.youtube.com/watch?v=jJhbXriDxpw,TOP—5. Best Budget Gaming Monitors (Under $100...,2026-03-14 22:00:42+00:00,5m 15s,315,"[comparison, cpu, gpu, intel, amd, nvidia, gef...",‎Amazon Basics ‎24E2QA\nAmazon https://flozes....,82,0,0,True,[ad],True,5,[https://flozes.com/a?shop=aus&id=Amazon-Basic...

In [21]:
short_video = df['duration_seconds'] <= 60

df['is_short'] = short_video

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1150 entries, 0 to 1399
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   channel_id            1150 non-null   object
 1   video_id              1150 non-null   object
 2   video_url             1150 non-null   object
 3   title                 1150 non-null   object
 4   published_at          1150 non-null   datetime64[ns, UTC]
 5   duration              1150 non-null   object
 6   duration_seconds      1150 non-null   int64
 7   tags                  1150 non-null   object
 8   description           1150 non-null   object
 9   view_count            1150 non-null   int64
 10  like_count            1150 non-null   int64
 11  comment_count         1150 non-null   int64
 12  has_ad_keywords       1150 non-null   bool
 13  matched_ad_keywords   1150 non-null   object
 14  has_external_links    1150 non-null   bool
 15  external_links_count  1150 non-null   int64
 16  external_links        1150 non-null   object
 17  is_short              1150 non-null   bool
dtypes: bool(3), datetime64[ns, UTC](1), int64(5), object(9)
memory usage: 179.4+ KB

In [23]:
df

,channel_id,video_id,video_url,title,published_at,duration,duration_seconds,tags,description,view_count,like_count,comment_count,has_ad_keywords,matched_ad_keywords,has_external_links,external_links_count,external_links,is_short
0,UCt7sv-NKh44rHAEb-qCCxvA,ZUU3OIfSRNE,https://www.youtube.com/watch?v=ZUU3OIfSRNE,"Умные шахматы, где фигуры движутся сами! Магия!",2026-03-19 16:20:59+00:00,15m 9s,909,"[iPhone, Apple, wylsa, Wylsacom, Айфон, Вилса,...",Лимитированный игровой ноутбук MSI Titan Drago...,13018,1458,104,True,[реклама],True,8,"[https://clck.ru/3Sdtu3, https://t.me/Wylsared...",False
1,UCt7sv-NKh44rHAEb-qCCxvA,pZSK9k7RdpA,https://www.youtube.com/watch?v=pZSK9k7RdpA,"Посылки из Китая: ОЧЕНЬ дорогой регистратор, M...",2026-03-17 15:20:53+00:00,21m 16s,1276,"[iPhone, Apple, wylsa, Wylsacom, Айфон, Вилса,...",Илья в Телеграме — https://t.me/kazakof\nНаши ...,122067,2621,169,True,[реклама],True,13,"[https://t.me/kazakof, https://biggeek.ru, htt...",False
2,UCt7sv-NKh44rHAEb-qCCxvA,KF73tDDafwk,https://www.youtube.com/watch?v=KF73tDDafwk,Посылка от подписчика для Wylsacom и его больш...,2026-03-17 11:42:15+00:00,1m 29s,89,[],,204982,4081,68,False,[],False,0,[],False
3,UCt7sv-NKh44rHAEb-qCCxvA,Ij5lid7NzXo,https://www.youtube.com/watch?v=Ij5lid7NzXo,Когда тест пошёл не по плану!,2026-03-15 09:58:57+00:00,22s,22,[],,636113,6446,131,False,[],False,0,[],True
4,UCt7sv-NKh44rHAEb-qCCxvA,Wh6Tz00KpbQ,https://www.youtube.com/watch?v=Wh6Tz00KpbQ,Новый MacBook Neo vs. игры. Бессмысленно и бес...,2026-03-14 15:14:26+00:00,13m 17s,797,"[iPhone, Apple, wylsa, Wylsacom, Айфон, Вилса,...",Илья в Телеграме — https://t.me/kazakof\nНаши ...,241578,5639,482,True,[реклама],True,9,"[https://t.me/kazakof, https://biggeek.ru, htt...",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1395,UCA-JK7chBxEsGHQs3m6UK5A,orbeWPH8XCs,https://www.youtube.com/watch?v=orbeWPH8XCs,TOP—5. Best Gaming Monitors (144Hz–165Hz) Febr...,2026-02-23 22:01:00+00:00,32s,32,"[comparison, cpu, gpu, intel, amd, nvidia, gef...",,840,5,0,False,[],False,0,[],True
1396,UCA-JK7chBxEsGHQs3m6UK5A,px3nom_-Y6I,https://www.youtube.com/watch?v=px3nom_-Y6I,TOP—5. Best Workstation Laptops 2026,2026-02-23 22:00:54+00:00,5m 24s,324,"[comparison, cpu, gpu, intel, amd, nvidia, gef...",HP ‎TPN-I139\nAmazon https://flozes.com/a?shop...,200,2,1,True,[ad],True,5,[https://flozes.com/a?shop=aus&id=HP-TPN-I139-...,False
1397,UCA-JK7chBxEsGHQs3m6UK5A,_ZmC7Kg2H7E,https://www.youtube.com/watch?v=_ZmC7Kg2H7E,Dell S2425HSM Monitor | TEST | English,2026-02-23 18:00:46+00:00,3m 59s,239,"[comparison, cpu, gpu, intel, amd, nvidia, gef...",Amazon https://flozes.com/a?shop=aus&id=Dell-S...,394,5,2,False,[],True,1,[https://flozes.com/a?shop=aus&id=Dell-S2425HS...,False
1398,UCA-JK7chBxEsGHQs3m6UK5A,dOjsTS_qCiI,https://www.youtube.com/watch?v=dOjsTS_qCiI,TOP—5. Best Gaming Monitors (360Hz–540Hz) Marc...,2026-02-23 00:00:40+00:00,5m 46s,346,"[comparison, cpu, gpu, intel, amd, nvidia, gef...",LG ‎27G810A-B.AUS\nAmazon https://flozes.com/a...,99,5,1,False,[],True,5,[https://flozes.com/a?shop=aus&id=LG-27G810A-B...,False
1399,UCA-JK7chBxEsGHQs3m6UK5A,Yssj-DxENaA,https://www.youtube.com/watch?v=Yssj-DxENaA,TOP—5. Best Gaming Monitors (144Hz–165Hz) Marc...,2026-02-22 22:00:36+00:00,5m 14s,314,"[comparison, cpu, gpu, intel, amd, nvidia, gef...",‎Dell 24 Plus Monitor - S2425HSM\nAmazon https...,84,2,1,False,[],True,5,[https://flozes.com/a?shop=aus&id=Dell-24-Plus...,False

In [24]:
# description ішіндегі \n жою
df['description'] = df['description'].str.replace('\n', ' ', regex=False)

In [25]:
df['description'].head(10)

0    Лимитированный игровой ноутбук MSI Titan Drago...
1    Илья в Телеграме — https://t.me/kazakof Наши с...
2
3
4    Илья в Телеграме — https://t.me/kazakof Наши с...
5
6    Производитель машины — компания EVM (ЭМ Рус (Э...
7
8    Выгода 10% по промокоду WYLSA на кофемашины Ju...
9    Лучший магазин гаджетов: https://biggeek.ru  Р...
Name: description, dtype: object

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1150 entries, 0 to 1399
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   channel_id            1150 non-null   object
 1   video_id              1150 non-null   object
 2   video_url             1150 non-null   object
 3   title                 1150 non-null   object
 4   published_at          1150 non-null   datetime64[ns, UTC]
 5   duration              1150 non-null   object
 6   duration_seconds      1150 non-null   int64
 7   tags                  1150 non-null   object
 8   description           1150 non-null   object
 9   view_count            1150 non-null   int64
 10  like_count            1150 non-null   int64
 11  comment_count         1150 non-null   int64
 12  has_ad_keywords       1150 non-null   bool
 13  matched_ad_keywords   1150 non-null   object
 14  has_external_links    1150 non-null   bool
 15  external_links_count  1150 non-null   int64
 16  external_links        1150 non-null   object
 17  is_short              1150 non-null   bool
dtypes: bool(3), datetime64[ns, UTC](1), int64(5), object(9)
memory usage: 179.4+ KB

In [32]:
df.to_csv('videos_cleaned_new.csv', index=False)